# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - vscjava.vscode-lombok
    - eamodio.gitlens
    - felipecaputo.git-project-manager
    - dbaeumer.vscode-eslint
    - ms-vscode.cpptools-extension-pack
    - evondev.indent-rainbow-palettes
    - donjayamanne.git-extension-pack
    - esbenp.prettier-vscode
    - redhat.vscode-xml
    - rangav.vscode-thunder-client
    - developersoapbox.vscode-springboot-developer-pack
    - ms-azuretools.vscode-dapr
    - bierner.markdown-preview-github-styles
    - oderwat.indent-rainbow
    - cweijan.git-graph-history
    - mhutchie.git-graph
    - ms-vscode.makefile-tools
    - mongodb.mongodb-vscode 
