server:
    port: 7001
    error:
        include-message: always

spring:
    application:
        name: user-service

    data:
        mongodb:
            uri: mongodb://root:rootuser@localhost:27017/userdb?authSource=admin&authMechanism=SCRAM-SHA-1
            # host: localhost
            # port: 27017
            #database: user_db
            #username: mando
            #password: mantung
            #authentication-database: testdb

    # RabbitMQ parameters
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest
    # Messaging binders for the cloud streaming
    cloud:
        stream:
            default-binder: rabbit
            bindings:
                input:
                    destination: users
                    group: usersGroup
                    binder: rabbit
# Use the consumer function name as input to 
# create destination and group in 3.0+
                userConsumer-in-0:
                    destination: users
                    group: usersGroup
# Consumer input binding parameters
            #bindings:
                #userConsumer-in-0
                    consumer:
                        maxAttempts: 3
                        backOffInitialInterval: 500
                        backOffMaxInterval: 1000
                        backOffMultiplier: 2.0
# RabbitMQ consumer input binding parameters
            rabbit:
                bindings:
                    userConsumer-in-0:
                        consumer:
                            auto-bind-dlq: true
                            republishToDlq: true
# Kafka consumer input binding parameters
            kafka:
                bindings:
                    userConsumer-in-0:
                        consumer:
                            enableDlq: true
# logging level
logging:
    level:
        root: INFO
        com:
            minejava: DEBUG
        org:
            springframework:
                amqp: DEBUG
                data.mongodb.core.MongoTemplate: DEBUG


# Actuator endpoints
management:
    endpoints:
        health:
            show-details: "ALWAYS"
    web:
        exposure:
            include: "*"



